site_name: Glossary
nav:
  - Home: index.md
  - INTRO: intro.md
  - MkDocs_usage: MkDocs_usage.md
  - Medical glossary:
      - Medical glossary-1: medical-glossary-1.md
      - Oncology glossary-1: oncology-glossary-1.md
  - Philosophy:
      - EN: en/en__philosophy_glossary_1.md
      - UA: uk/ua__philosophy_glossary_1.md
  - Trading:
      - EN: en/en__trading_glossary_1.md
theme: readthedocs
extra_css:
  - css/customWidth.css
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Ukraine
      link: /uk/
      lang: uk
plugins:
  - search:
      prebuild_index: true
      encoding: 'utf-8'
      lang:
        - en
        - ru
        - uk