site_name: Glossary
nav:
  - Home: index.md
  - MkDocs_usage: MkDocs_usage.md
  - Glossary:
      - Med glossary-1: med_glos_1_1.md
theme: readthedocs
extra_css:
  - css/customWidth.css
plugins:
  - search:
      prebuild_index: true
      encoding: 'utf-8'
      lang:
        - en
        - ru